## Atividade 1

In [1]:
import numpy as np

size = 20

F1 = np.random.randint(low=0, high=10, size=size, dtype=int)

for i in range (size):
    F1[i] = int(input())
    
F2 = np.zeros(size,dtype=int)

for i in range (size):
    if i == 0:
        F2[i] = min(F1[size-1],F1[i],F1[i+1])
    elif i == size-1:
        F2[i] = min(F1[i-1],F1[i],F1[0])
    else:
        F2[i] = min(F1[i-1],F1[i],F1[i+1])
        
print(F2)

5
4
8
4
6
6
6
0
3
3
0
4
2
3
3
1
2
2
8
7
[4 4 4 4 4 6 0 0 0 0 0 0 2 2 1 1 1 2 2 5]


## Atividade 2

In [2]:
b_origem = int(input())
b = []
f = []
for i in range (5):
    b.append(int(input()))
#b = [2, 0, 0, 0, 2]
for i in range (25):
    f.append(int(input()))
#f = [6, 5, 3, 2, 3, 6, 3, 4, 2, 6, 5, 5, 4, 5, 4, 3, 2, 5, 5, 6, 3, 5, 2, 2, 3]

aux = []

for i in range (25):
    if i == 0:
        aux.append(min(f[i]-b[b_origem],f[i+1]-b[b_origem+1]))
    elif i == 1:
        aux.append(min(f[i-1]-b[b_origem-1],f[i]-b[b_origem],f[i+1]-b[b_origem+1]))
    elif i == 2:
        aux.append(min(f[i-2]-b[b_origem-2],f[i-1]-b[b_origem-1],f[i]-b[b_origem],f[i+1]-b[b_origem+1]))
    elif i == 24:
        aux.append(min(f[i-3]-b[b_origem-3],f[i-2]-b[b_origem-2],f[i-1]-b[b_origem-1],f[i]-b[b_origem]))
    else:
        aux.append(min(f[i-3]-b[b_origem-3],f[i-2]-b[b_origem-2],f[i-1]-b[b_origem-1],f[i]-b[b_origem],f[i+1]-b[b_origem+1]))
        
print(aux)

3
2
0
0
0
2
6
5
3
2
3
6
3
4
2
6
5
5
4
5
4
3
2
5
5
6
3
5
2
2
3
[3, 1, 0, 1, 2, 1, 0, 0, 2, 1, 2, 0, 3, 2, 1, 0, 2, 2, 1, 0, 3, 0, 0, 1, 2]


## Atividade 3

In [3]:
import numpy as np

#b = [-3, -2, 0, -2, -3]
#f = [9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9]

b = []
f = []

for i in range (5):
    b.append(int(input()))
    
for i in range (32):
    f.append(int(input()))

def myDistance(f,b):
    n = 0
    g = f
    while True:
        n = n+1
        f = g
        g = myErosion(g,b)
        if np.array_equal(f,g): break
    return g,n

def myErosion(f,b):
    L = len(f)
    Lb = len(b)
    g = f.copy()
    for l in range(L):
        for x in range(Lb):
            i = int(l+x-Lb/2+.5)
            if i >= 0 and i < L:
                if g[l] > f[i]-b[x]:
                    g[l] = f[i]-b[x]
    return g

f,n = myDistance(f,b)
#print([9, 8, 6, 5, 3, 2, 0, 2, 3, 5, 6, 8, 6, 5, 3, 2, 0, 2, 3, 5, 6, 8, 6, 5, 3, 2, 0, 2, 3, 5, 6, 8])
print(f)
print(n)

-3
-2
0
-2
-3
9
9
9
9
9
9
0
9
9
9
9
9
9
9
9
9
0
9
9
9
9
9
9
9
9
9
0
9
9
9
9
9
[9, 8, 6, 5, 3, 2, 0, 2, 3, 5, 6, 8, 6, 5, 3, 2, 0, 2, 3, 5, 6, 8, 6, 5, 3, 2, 0, 2, 3, 5, 6, 8]
4


## Atividade 4

A atividade foi diferente do sistema.

In [4]:
import numpy as np

b = np.zeros((3,4),dtype=int)
f = np.zeros((7,6),dtype=int)

def dilatacao(f,b):
    L,C = f.shape
    Lb,Cb = b.shape
    g = f.copy()
    for l in range(L):
        for c in range(C):
            for x in range(Lb):
                for y in range(Cb):
                    i = int(l+x-Lb/2+.5)
                    j = int(c+y-Cb/2+.5)
                    if i>=0 and i<L and j>=0 and j<C:
                        if g[l,c] < f[i,j]+b[x,y]:
                            g[l,c]= f[i,j]+b[x,y]
    return g

#for i in range (3):
#    for j in range (4):
#        b[i,j] = int(input())
        
#for i in range (7):
#    for j in range (6):
#        f[i,j] = int(input())

b = np.array([[0, 0, 1, 1],
              [1, 0, 0, 0],
              [0, 0, 1, 0]],dtype=int)

f = np.array([[0, 4, 6, 0, 4, 4],
              [0, 4, 2, 6, 2, 4],
              [2, 6, 6, 2, 0, 2],
              [2, 0, 2, 2, 6, 0],
              [6, 6, 2, 6, 0, 0],
              [4, 4, 0, 2, 0, 0],
              [8, 2, 2, 4, 4, 4]],dtype=int)

f = dilatacao(f,b)

#for i in range (7):
#    for j in range (6):
#        print(f[i,j])
print(f)

[[4 6 6 7 7 6]
 [6 7 7 6 6 7]
 [6 6 7 7 7 6]
 [7 7 7 7 6 6]
 [6 7 7 7 7 7]
 [9 8 8 7 6 6]
 [8 9 9 4 4 5]]


## Atividade 5

In [5]:
import numpy as np

b = np.zeros((3,2),dtype=int)
f = np.zeros((8,7),dtype=int)

def erosao(f,b):
    L,C = f.shape
    Lb,Cb = b.shape
    g = f.copy()
    for l in range(L):
        for c in range(C):
            for x in range(Lb):
                for y in range(Cb):
                    i = int(l+x-Lb/2+.5)
                    j = int(c+y-Cb/2+.5)
                    if i>=0 and i<L and j>=0 and j<C:
                        if g[l,c] > f[i,j]-b[x,y]:
                            g[l,c]= f[i,j]-b[x,y]
    return g

def dilatacao(f,b):
    L,C = f.shape
    Lb,Cb = b.shape
    g = f.copy()
    for l in range(L):
        for c in range(C):
            for x in range(Lb):
                for y in range(Cb):
                    i = int(l+x-Lb/2+.5)
                    j = int(c+y-Cb/2+.5)
                    if i>=0 and i<L and j>=0 and j<C:
                        if g[l,c] < f[i,j]+b[x,y]:
                            g[l,c]= f[i,j]+b[x,y]
    return g

#for i in range (3):
#    for j in range (2):
#        b[i,j] = int(input())
        
#for i in range (8):
#    for j in range (7):
#        f[i,j] = int(input())

b = np.array([[0, 1],
              [0, 0],
              [1, 1]],dtype=int)

f = np.array([[7, 5, 1, 3, 3, 3, 5],
              [5, 3, 1, 5, 1, 5, 1],
              [7, 3, 1, 5, 1, 5, 3],
              [3, 5, 3, 1, 1, 7, 7],
              [3, 1, 3, 3, 5, 1, 1],
              [3, 1, 1, 5, 5, 3, 7],
              [7, 7, 1, 1, 1, 7, 1],
              [5, 1, 5, 1, 5, 5, 1]],dtype=int)

f = f - dilatacao(erosao(f,b),b)

#for i in range (7):
#    for j in range (6):
#        print(f[i,j])
print(f)

[[ 1 -1 -2  2  2  2  3]
 [ 0 -2 -2  4  0  4  0]
 [ 1 -2 -1  3 -1  4  1]
 [ 0  2  1  0  0  5  5]
 [ 0 -2  2  1  4  0  0]
 [ 0 -2  0  4  4  1  5]
 [ 1  1 -1  0  0  5 -1]
 [ 0 -4  4  0  4  3  0]]


## Atividade 6

In [6]:
import numpy as np

def not_empty(f):
    L,C = f.shape
    for l in range(L):
        for c in range(C):
            if (f[l,c]==1):
                return 1
    return 0

def erosao(f,b):
    L,C = f.shape
    Lb,Cb = b.shape
    g = f.copy()
    for l in range(L):
        for c in range(C):
            for x in range(Lb):
                for y in range(Cb):
                    i = int(l+x-Lb/2+.5)
                    j = int(c+y-Cb/2+.5)
                    if i>=0 and i<L and j>=0 and j<C:
                        if g[l,c] > f[i,j]-b[x,y]:
                            g[l,c]= f[i,j]-b[x,y]
    return g

def dilatacao(f,b):
    L,C = f.shape
    Lb,Cb = b.shape
    g = f.copy()
    for l in range(L):
        for c in range(C):
            for x in range(Lb):
                for y in range(Cb):
                    i = int(l+x-Lb/2+.5)
                    j = int(c+y-Cb/2+.5)
                    if i>=0 and i<L and j>=0 and j<C:
                        if g[l,c] < f[i,j]+b[x,y]:
                            g[l,c]= f[i,j]+b[x,y]
    return g

#b = np.zeros((3,3),dtype=int)
#f = np.zeros((8,9),dtype=int)
skel = np.zeros((8,9),dtype=int)

#for i in range (3):
#    for j in range (3):
#        b[i,j] = int(input())
        
#for i in range (8):
#    for j in range (9):
#        f[i,j] = int(input())

b = np.array([[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]],dtype=int)

f = np.array([[1, 1, 1, 0, 0, 0, 0, 0, 0],
              [1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1, 1, 1, 1, 1],
              [0, 0, 0, 1, 1, 1, 1, 1, 1]],dtype=int)

notopen = 0
fandnop = 0
sorf = 0
    
while (not_empty(f)):
    openf = dilatacao(erosao(f,b),b)
    for l in range(8):
        for c in range(9):
            notopen = np.logical_not(openf[l,c]).astype(int)
            fandnop = np.logical_and(f[l,c],(notopen)).astype(int)
            sorf = np.logical_or(skel[l,c],fandnop).astype(int)
            skel[l,c] = sorf
    f = erosao(f,b);

#for i in range (8):
#    for j in range (9):
#        print(skel[i,j])    

print(skel)

[[1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1]]


## Atividade 7

In [7]:
import numpy as np

def erosao(f,b):
    L,C = f.shape
    Lb,Cb = b.shape
    g = f.copy()
    for l in range(L):
        for c in range(C):
            for x in range(Lb):
                for y in range(Cb):
                    i = int(l+x-Lb/2+.5)
                    j = int(c+y-Cb/2+.5)
                    if i>=0 and i<L and j>=0 and j<C:
                        if g[l,c] > f[i,j]-b[x,y]:
                            g[l,c]= f[i,j]-b[x,y]
    return g

b = np.zeros((3,3),dtype=int)

#f = np.zeros((8,9),dtype=int)

f = np.array([[99, 99, 99, 99, 99, 99, 99, 99, 99],
              [99, 99, 99, 99, 99,  0, 99, 99, 99],
              [99, 99, 99, 99, 99, 99, 99, 99, 99],
              [99, 99, 99, 99, 99, 99,  0, 99,  0],
              [99, 99, 99, 99, 99, 99, 99, 99, 99],
              [99, 99, 99, 99, 99, 99, 99, 99, 99],
              [99,  0, 99, 99,  0, 99, 99, 99, 99],
              [99, 99, 99, 99, 99, 99, 99, 99, 99]],dtype=int)

#for i in range (8):
#    for j in range (9):
#        f[i,j] = int(input())

i = 0

g = f.copy()
while True:
    i = i+1
    b = np.array([[-4*i + 2, -2*i + 1, -4*i + 2],
                  [-2*i + 1,        0, -2*i + 1],
                  [-4*i + 2, -2*i + 1, -4*i + 2]],dtype=int)
    f = g.copy()
    g = erosao(g,b)
    if np.array_equal(f,g):
        break

print(f'resultado:\n{g}')
print(f'iterações: {i}')

resultado:
[[26 17 10  5  2  1  2  5  9]
 [25 16  9  4  1  0  1  4  4]
 [17 16 10  5  2  1  1  2  1]
 [10  9 10  8  4  1  0  1  0]
 [ 5  4  5  5  4  2  1  2  1]
 [ 2  1  2  2  1  2  4  5  4]
 [ 1  0  1  1  0  1  4  9  9]
 [ 2  1  2  2  1  2  5 10 16]]
iterações: 6
